#!/usr/bin/bash

ip=$1
server_port=$2

[ -z "$ip" ] && echo Empty argument "'ip'" && exit 1
[ -z "$server_port" ] && echo Empty argument "'server_port'" && exit 1

python3 monitoring/client_main.py $ip $server_port "${@:3}"
